name: "AppRunner Monolitic"
run-name: "AppRunner Monolitic"
on:
  workflow_dispatch:
    inputs:
      cloud:
        description: "Steps"
        required: true
        default: "build"
        options: ["All", "build", "deploy-create", "deploy-update"]
jobs:
  build:
    if: ${{ github.event.inputs.cloud == 'build' }}
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repositorio"
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f #v3: v3.4.0
      - name: "Configurar QEMU"
        uses: docker/setup-qemu-action@e81a89b1732b9c48d79cd809d8d81d79c4647a18 #v2: v2.1.0
      - name: "Configurar Docker Buildx"
        uses: docker/setup-buildx-action@4b4e9c3e2d4531116a6f8ba8e71fc6e2cb6e6c8c #v2: v2.5.0
      - name: "Configurar tag y etiquetas para ${{ github.ref }}"
        run: |
          if [ "$GITHUB_REF" == "refs/heads/main" ]; then
          echo "DOCKER_TAG=latest-apprunnerM" >> $GITHUB_ENV
          else
          echo "DOCKER_TAG=${{ github.ref_name }}-apprunnerM" >> $GITHUB_ENV
          fi
      - name: "Configurar credenciales de AWS"
        uses: aws-actions/configure-aws-credentials@e1e17a757e536f70e52b5a12b2e8d1d1c60e04ef #v2 #v2.0.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
      - name: "Autenticar en AWS ECR"
        id: login-ecr-publico
        uses: aws-actions/amazon-ecr-login@261a7de32bda11ba01f4d75c4ed6caf3739e54be #v1 #v1.5.3
        with:
          registry-type: public
      - name: "Compilar y Subir imagen de Docker"
        env:
          REGISTRY: ${{ steps.login-ecr-publico.outputs.registry }}
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671 #v4 #v4.0.0
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ vars.AWS_REGISTRY_ALIAS }}/${{ vars.IMAGE_NAME }}:${{ env.DOCKER_TAG }}
