name: "AppRunner Monolitic"
run-name: "AppRunner Monolitic"
on:
  workflow_dispatch:
    inputs:
      cloud:
        description: "Steps"
        required: true
        default: "build"
        type: choice
        options: ["All", "build", "deploy-create", "deploy-update"]
jobs:
  build:
    if: ${{ github.event.inputs.cloud == 'build' }}
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repositorio"
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f #v3: v3.4.0
      - name: "Configurar QEMU"
        uses: docker/setup-qemu-action@e81a89b1732b9c48d79cd809d8d81d79c4647a18 #v2: v2.1.0
      - name: "Configurar Docker Buildx"
        uses: docker/setup-buildx-action@4b4e9c3e2d4531116a6f8ba8e71fc6e2cb6e6c8c #v2: v2.5.0
      - name: "Configurar tag y etiquetas para ${{ github.ref }}"
        run: |
          if [ "$GITHUB_REF" == "refs/heads/main" ]; then
          echo "DOCKER_TAG=latest-apprunnerM" >> $GITHUB_ENV
          else
          echo "DOCKER_TAG=${{ github.ref_name }}-apprunnerM" >> $GITHUB_ENV
          fi
      - name: "Configurar credenciales de AWS"
        uses: aws-actions/configure-aws-credentials@e1e17a757e536f70e52b5a12b2e8d1d1c60e04ef #v2 #v2.0.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
      - name: "Autenticar en AWS ECR"
        id: login-ecr-publico
        uses: aws-actions/amazon-ecr-login@261a7de32bda11ba01f4d75c4ed6caf3739e54be #v1 #v1.5.3
        with:
          registry-type: public
      - name: "Preparar"
        working-directory: ./backstage
        run: > 
          yarn install --frozen-lockfile && 
          yarn tsc && 
          yarn build:backend --config ../../app-config.yaml
      - name: Build, tag, and push image to Amazon ECR
        id: build-publish
        working-directory: ./backstage
        env:
          REGISTRY: ${{ steps.login-ecr-publico.outputs.registry }}
        run: |
          docker image build . -f packages/backend/Dockerfile -t "${{ env.REGISTRY }}/${{ vars.AWS_REGISTRY_ALIAS }}/${{ vars.IMAGE_NAME }}:${{ env.DOCKER_TAG }}"
          docker push "${{ env.REGISTRY }}/${{ vars.AWS_REGISTRY_ALIAS }}/${{ vars.IMAGE_NAME }}:${{ env.DOCKER_TAG }}"
          echo "full_image=${{ env.REGISTRY }}/${{ vars.AWS_REGISTRY_ALIAS }}/${{ vars.IMAGE_NAME }}:${{ env.DOCKER_TAG }}"
  deploy-create:
    runs-on: ubuntu-latest
    if: github.event.inputs.cloud == 'deploy-create'
    steps:
      - name: "Configurar tag y etiquetas para ${{ github.ref }}"
        run: |
          if [ "$GITHUB_REF" == "refs/heads/main" ]; then
          echo "DOCKER_TAG=latest-apprunnerM" >> $GITHUB_ENV
          else
          echo "DOCKER_TAG=${{ github.ref_name }}-apprunnerM" >> $GITHUB_ENV
          fi
      - name: "Configurar credenciales de AWS"
        uses: aws-actions/configure-aws-credentials@e1e17a757e536f70e52b5a12b2e8d1d1c60e04ef #v2 #v2.0.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
      - name: Crear archivo de configuración para AppRunner
        run:  |
          echo '{
            "ServiceName": "${{ vars.IMAGE_NAME }}",
            "SourceConfiguration": {
                "ImageRepository": {
                    "ImageIdentifier": "${{ vars.AWS_REGISTRY }}/${{ vars.AWS_REGISTRY_ALIAS }}/${{ vars.IMAGE_NAME }}:${{ env.DOCKER_TAG }}",
                    "ImageRepositoryType": "ECR_PUBLIC"
                },
                "AutoDeploymentsEnabled": false
            },
            "InstanceConfiguration": {
               "Cpu": "0.25 vCPU",
               "Memory": "0.5 GB"
            }
          }' > apprunner.json
      - name: Deploy app en AWS App Runner
        id: deploy-apprunner
        run: |
          aws apprunner create-service \
            --cli-input-json file://apprunner.json
      - name: App Runner URL
        run: echo "App runner URL ${{ steps.deploy-apprunner.outputs.service.serviceUrl }}" 
